export default [
  `Kitsch praxis four loko disrupt tbh gluten-free kale chips whatever. Humblebrag flannel af literally, hoodie bushwick venmo tacos lomo squid man braid cornhole hella readymade. Twee selvage tbh vinyl fixie jawn raclette offal wolf portland big mood art party street art. Sus fingerstache jawn, jianbing taiyaki letterpress scenester drinking vinegar disrupt mustache.`,
  `Brooklyn intelligentsia hammock taxidermy. Poutine big mood chicharrones, pitchfork kinfolk kogi next level. Shoreditch tofu bitters messenger bag, selfies asymmetrical vinyl master cleanse ethical you probably haven't heard of them narwhal. Succulents selvage ascot PBR&B. Marxism paleo selvage brunch four dollar toast. Distillery synth deep v, wayfarers cornhole knausgaard praxis farm-to-table migas poutine microdosing. Bicycle rights kitsch tonx polaroid, gentrify ethical photo booth try-hard synth mustache ascot.`,
  `Shoreditch meggings 8-bit, paleo everyday carry tofu sriracha activated charcoal leggings vaporware vape meditation. Drinking vinegar brunch next level Brooklyn jean shorts, snackwave disrupt dreamcatcher. Flannel celiac praxis, tbh bushwick 3 wolf moon before they sold out. Big mood la croix listicle, Brooklyn cupping authentic slow-carb same fashion axe. Small batch fanny pack godard, migas man bun mlkshk neutral milk hotel actually master cleanse literally. Scenester retro roof party vape migas sustainable bicycle rights cray bitters heirloom bruh pinterest slow-carb Brooklyn.`,
  `Tbh gatekeep taiyaki cloud bread. Grailed enamel pin activated charcoal plaid sartorial food truck. Organic cronut vaporware selfies 90's. Kombucha copper mug PBR&B intelligentsia chillwave, pug four dollar toast tumeric tbh trust fund master cleanse small batch slow-carb same glossier.`,
  `Street art forage fixie, etsy small batch polaroid DIY flexitarian celiac schlitz asymmetrical gorpcore selfies lumbersexual hot chicken. Vaporware PBR&B crucifix, chambray hexagon authentic echo park DIY edison bulb. Poke whatever hoodie distillery mustache air plant leggings. Iceland leggings heirloom dreamcatcher.`,
  `Hexagon cornhole squid offal tumeric synth single-origin coffee scenester neutral milk hotel salvia viral lo-fi same. Portland narwhal salvia humblebrag tilde. Vegan subway tile venmo yuccie marfa. Pickled cloud bread tumblr snackwave gatekeep. Williamsburg vaporware gluten-free cupping man braid mukbang next level shaman.`,
  `Echo park polaroid dreamcatcher pitchfork. Lo-fi snackwave dreamcatcher hot chicken post-ironic gatekeep sartorial pitchfork master cleanse. Photo booth bicycle rights poke art party jianbing gluten-free celiac hammock kickstarter master cleanse. Forage tumeric vegan hoodie praxis chartreuse. Chicharrones pop-up kombucha pork belly. Blog cupping umami sriracha pug single-origin coffee cronut hashtag bicycle rights. Kinfolk chicharrones microdosing vinyl swag asymmetrical organic scenester pour-over sriracha.`,
  `Celiac readymade roof party YOLO bespoke flexitarian letterpress chicharrones wolf XOXO schlitz. Mumblecore man bun chicharrones live-edge banh mi austin pok pok franzen skateboard keffiyeh kogi tote bag four dollar toast. Cornhole tacos art party, copper mug stumptown chartreuse taxidermy schlitz lo-fi yuccie. Palo santo kinfolk fashion axe XOXO subway tile microdosing. Tofu fixie cray paleo disrupt, franzen affogato pork belly keffiyeh edison bulb roof party mlkshk.`,
  `Fashion axe air plant 8-bit chicharrones aesthetic. Farm-to-table roof party jean shorts distillery cornhole paleo, narwhal marfa tousled quinoa microdosing raw denim master cleanse crucifix. Ethical kickstarter bicycle rights, VHS poke man braid etsy brunch tumblr same activated charcoal ramps enamel pin vice. Pug man bun drinking vinegar 90's, austin 8-bit butcher tonx gluten-free hashtag brunch cold-pressed disrupt hammock. Man braid ramps fixie vaporware try-hard viral gorpcore. Plaid tofu adaptogen, umami deep v jianbing bushwick blue bottle air plant synth DSA vape cardigan sartorial mustache.`,
  `Chambray man bun fit, hoodie banh mi DSA street art semiotics hella fixie drinking vinegar. Squid hammock freegan gatekeep cupping drinking vinegar helvetica. Raw denim biodiesel activated charcoal pop-up semiotics bicycle rights keffiyeh taiyaki ethical DIY pug meh. Gatekeep narwhal crucifix, scenester health goth af vexillologist. Cornhole activated charcoal raw denim 8-bit sus drinking vinegar kogi praxis.`,
];
