export default [
  {
    id: 1,
    name: "Bob Jones",
    image: "src/assets/team-1.jpg",
    dob: { year: 1990, month: 11, day: 27 },
    job: "Web Developer",
    text: "Vestibulum lectus mauris ultrices eros in cursus. Arcu dictum varius duis at consectetur. In metus vulputate eu scelerisque felis imperdiet proin. Lacus luctus accumsan tortor posuere ac. Ligula ullamcorper malesuada proin libero nunc. Blandit cursus risus at ultrices mi tempus imperdiet nulla. Viverra nam libero justo laoreet sit. Nec nam aliquam sem et tortor. Cursus sit amet dictum sit amet justo donec enim. Mauris commodo quis imperdiet massa tincidunt nunc.",
  },
  {
    id: 2,
    name: "Jill Bailey",
    image: "src/assets/team-2.jpg",
    dob: { year: 1996, month: 1, day: 27 },
    job: "Web Designer",
    text: "Dui id ornare arcu odio ut sem. At urna condimentum mattis pellentesque id nibh. Pellentesque adipiscing commodo elit at imperdiet dui. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis. Duis at tellus at urna condimentum mattis pellentesque id. Accumsan lacus vel facilisis volutpat est velit egestas dui. Dignissim diam quis enim lobortis scelerisque. In est ante in nibh mauris. Sit amet consectetur adipiscing elit.",
  },
  {
    id: 3,
    name: "Gail Shepherd",
    image: "src/assets/team-3.jpg",
    dob: { year: 1992, month: 11, day: 27 },
    job: "Project Manager",
    text: "Et netus et malesuada fames ac turpis. Non enim praesent elementum facilisis leo vel fringilla est ullamcorper. Mi tempus imperdiet nulla malesuada pellentesque elit. Elit at imperdiet dui accumsan. Vel orci porta non pulvinar neque laoreet suspendisse. Magnis dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae.",
  },
  {
    id: 4,
    name: "Sam Reynolds",
    image: "src/assets/team-4.jpg",
    dob: { year: 1991, month: 5, day: 12 },
    job: "Cloud Engineer",
    text: "Dui id ornare arcu odio ut sem. At urna condimentum mattis pellentesque id nibh. Pellentesque adipiscing commodo elit at imperdiet dui. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis. Duis at tellus at urna condimentum mattis pellentesque id. Accumsan lacus vel facilisis volutpat est velit egestas dui. Dignissim diam quis enim lobortis scelerisque. In est ante in nibh mauris. Sit amet consectetur adipiscing elit.",
  },
  {
    id: 5,
    name: "David Henry",
    image: "src/assets/team-5.jpg",
    dob: { year: 1993, month: 11, day: 26 },
    job: "Azure Developer",
    text: "Fermentum iaculis eu non diam phasellus vestibulum lorem sed risus. Ultricies leo integer malesuada nunc. Semper quis lectus nulla at volutpat diam ut venenatis. Magna fringilla urna porttitor rhoncus dolor. At tempor commodo ullamcorper a lacus vestibulum sed. Sem nulla pharetra diam sit amet. Enim diam vulputate ut pharetra sit amet. Egestas dui id ornare arcu odio ut sem nulla. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in.",
  },
  {
    id: 6,
    name: "Sarah Blake",
    image: "src/assets/team-6.jpg",
    dob: { year: 1998, month: 11, day: 27 },
    job: "Content Writer",
    text: "Non diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. At lectus urna duis convallis. Hac habitasse platea dictumst quisque sagittis purus sit amet volutpat. Risus pretium quam vulputate dignissim. Proin sagittis nisl rhoncus mattis. Felis donec et odio pellentesque diam volutpat commodo sed egestas. Pretium fusce id velit ut tortor pretium viverra. Nisl suscipit adipiscing bibendum est ultricies.",
  },
  {
    id: 7,
    name: "James Bennet",
    image: "src/assets/team-7.jpg",
    dob: { year: 1997, month: 8, day: 6 },
    job: "Mobile Developer",
    text: "Scelerisque in dictum non consectetur. Lectus arcu bibendum at varius vel. Sed elementum tempus egestas sed sed risus pretium quam vulputate. Et pharetra pharetra massa massa ultricies mi quis hendrerit. Sit amet justo donec enim diam vulputate ut pharetra. Elementum tempus egestas sed sed risus pretium. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. Enim neque volutpat ac tincidunt vitae.",
  },
  {
    id: 8,
    name: "Jessica Faye",
    image: "src/assets/team-8.jpg",
    dob: { year: 1994, month: 7, day: 2 },
    job: "IOS Mobile Developer",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At urna condimentum mattis pellentesque id nibh. Vel quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Venenatis cras sed felis eget. Consectetur a erat nam at lectus urna duis. Euismod lacinia at quis risus sed vulputate odio ut. Tincidunt id aliquet risus feugiat in ante metus dictum at.",
  },
  {
    id: 9,
    name: "Lita Stone",
    image: "src/assets/team-9.jpg",
    dob: { year: 1995, month: 9, day: 9 },
    job: "Social Media Manager",
    text: "Quis varius quam quisque id. Ultricies mi eget mauris pharetra et ultrices neque ornare. Euismod nisi porta lorem mollis aliquam ut porttitor leo. In dictum non consectetur a erat nam at lectus urna. Turpis nunc eget lorem dolor sed viverra ipsum. Euismod lacinia at quis risus sed vulputate odio ut. In est ante in nibh mauris cursus mattis molestie. Morbi non arcu risus quis varius quam. Id donec ultrices tincidunt arcu non sodales neque sodales. Lectus arcu bibendum at varius.",
  },
  {
    id: 10,
    name: "Daniel Young",
    image: "src/assets/team-10.jpg",
    dob: { year: 1999, month: 11, day: 27 },
    job: "AWS Engineer",
    text: " Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Quis enim lobortis scelerisque fermentum dui. Purus ut faucibus pulvinar elementum integer enim neque volutpat ac. Tellus id interdum velit laoreet id donec. Tortor at risus viverra adipiscing at. Viverra nam libero justo laoreet sit. Nec nam aliquam sem et tortor. Cursus sit amet dictum sit amet justo donec enim. Mauris commodo quis imperdiet massa tincidunt nunc.",
  },
  {
    id: 11,
    name: "Adrian Jacobs",
    image: "src/assets/team-11.jpg",
    dob: { year: 1998, month: 1, day: 25 },
    job: "Devops Engineer",
    text: "Arcu dictum varius duis at consectetur. In metus vulputate eu scelerisque felis imperdiet proin. Lacus luctus accumsan tortor posuere ac. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Quis enim lobortis scelerisque fermentum dui. Purus ut faucibus pulvinar elementum integer enim neque volutpat ac. Tellus id interdum velit laoreet id donec. Tortor at risus viverra adipiscing at. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Quis enim lobortis scelerisque fermentum dui.",
  },
  {
    id: 12,
    name: "Devin Monroe",
    image: "src/assets/team-12.jpg",
    dob: { year: 1992, month: 2, day: 27 },
    job: "Web Developer",
    text: "Cursus sit amet dictum sit amet justo donec enim. Mauris commodo quis imperdiet massa tincidunt nunc. Vestibulum lectus mauris ultrices eros in cursus. Arcu dictum varius duis at consectetur. In metus vulputate eu scelerisque felis imperdiet proin. Lacus luctus accumsan tortor posuere ac. Ligula ullamcorper malesuada proin libero nunc. Blandit cursus risus at ultrices mi tempus imperdiet nulla. Viverra nam libero justo laoreet sit. Nec nam aliquam sem et tortor. ",
  },
];
