import { useRef, useState } from "react";
import { FaMapMarkerAlt, FaTimesCircle, FaTrash } from "react-icons/fa";
import { IoIosSend } from "react-icons/io";
// npm install @react-google-maps/api
import {
  useJsApiLoader,
  GoogleMap,
  Marker,
  Autocomplete,
  DirectionsRenderer,
} from "@react-google-maps/api";

const googleMapsApiKey = import.meta.env.VITE_GOOGLE_MAP_KEY;
// In your https://console.cloud.google.com/ dashboard
// Create a project if you don't already have one
// API services
// Click on APIJSMap and Enable it

const center = { lat: 48.8584, lng: 2.2945 }; // coordinate for eiffel tower

// Mock data
const mockDeliveries = [
  {
    id: "DEL-78901",
    status: "in_transit",
    from: {
      name: "MediCare Pharmacy",
      address: "123 Pharmacy St, Victoria Island, Lagos",
      contact: "08012345678",
    },
    to: {
      name: "Jane Smith",
      address: "456 Residence Ave, Lekki Phase 1, Lagos",
      contact: "08087654321",
    },
    items: ["Paracetamol 500mg", "Vitamin C"],
    distance: "5.2 km",
    eta: "25 min",
    fee: "₦1,500",
    startedAt: "2023-05-15T11:30:00",
  },
  // Add more deliveries...
];

function NotLoaded() {
  return (
    <div className="text-center">
      <FaMapMarkerAlt className="mx-auto text-3xl text-red-500 mb-2" />
      <p className="text-gray-500 dark:text-gray-400">
        Map will display real-time navigation here
      </p>
    </div>
  );
}

function App() {
  const { isLoaded } = useJsApiLoader({
    googleMapsApiKey,
    libraries: ["places"], // populate input with places
  });

  // const [map, setMap] = useState(/** @type google.maps.Map */ (null));
  const [map, setMap] = useState(/** @type {google.maps.Map} */ (null));
  const [directionResponse, setDirectionResponse] = useState(null);
  const [distance, setDistance] = useState("");
  const [duration, setDuration] = useState("");
  const [showControls, setShowControls] = useState(false);

  /**@type {React.RefObject<HTMLInputElement>} */
  const originRef = useRef(null);
  /**@type {React.RefObject<HTMLInputElement>} */
  const destinationRef = useRef(null);

  // generated by AI
  /* function getDirections() {
    if (!map) return;
    const directionsService = new google.maps.DirectionsService();
    const directionsRenderer = new google.maps.DirectionsRenderer();
    directionsRenderer.setMap(map);
    directionsService.route(
      {
        origin: "123 Pharmacy St, Victoria Island, Lagos",
        destination: "456 Residence Ave, Lekki Phase 1, Lagos",
        travelMode: "DRIVING",
      },
      (response, status) => {
        if (status === "OK") {
          setDirectionResponse(response);
          setDistance(response.routes[0].legs[0].distance.text);
          setDuration(response.routes[0].legs[0].duration.text);
        }
      }
    );
  } */

  async function calculateRoute() {
    if (originRef.current.value === "" || destinationRef.current.value === "") {
      return;
    }
    const directionsService = new google.maps.DirectionsService();
    const results = await directionsService.route({
      origin: originRef.current.value,
      destination: destinationRef.current.value,
      travelMode: google.maps.TravelMode.DRIVING,
      // travelMode: "DRIVING",
    });
    setDirectionResponse(results);
    setDistance(results.routes[0].legs[0].distance.text);
    setDuration(results.routes[0].legs[0].duration.text);
  }

  function clearRoute() {
    setDirectionResponse(null);
    setDistance("");
    setDuration("");
    originRef.current.value = "";
    destinationRef.current.value = "";
  }

  return (
    <section className="bg-gray-900 flex justify-center items-center min-h-screen">
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md w-98/100 p-6">
        {!showControls && (
          <div className="flex justify-between">
            <h3 className="text-lg font-semibold mb-4 text-gray-800 dark:text-white">
              Delivery Route
            </h3>
            <button
              className="bg-blue-600 hover:bg-blue-800 text-white w-fit px-3 py-1 mb-2 rounded-lg cursor-pointer"
              onClick={() => setShowControls(true)}>
              Show Controls
            </button>
          </div>
        )}
        {showControls && (
          <div className="mb-2 mx-auto controls absolutetop-1left-[50%]translate-x-[-50%] max-w-138 w-full bg-gray-400 dark:bg-gray-700 p-2 rounded-lg">
            <div className="flex justify-between">
              <h3 className="text-lg font-semibold mb-4 text-gray-800 dark:text-white">
                Delivery Route
              </h3>
              <button
                className="close-btn text-lg text-red-500 mb-1 cursor-pointer"
                onClick={() => setShowControls(false)}>
                <FaTimesCircle />
              </button>
            </div>
            <div className="p-2 grid grid-cols-1 min-[340px]:grid-cols-2 min-[500px]:grid-cols-3 gap-2 justify-between">
              <Autocomplete>
                <input
                  type="text"
                  placeholder="From"
                  className="border border-blue-500 focus:ring-blue-500 outline-none ring-offset-2 focus:ring-2 rounded-lg w-full px-2 py-1 text-sm placeholder:text-gray-300 text-gray-300"
                  ref={originRef}
                />
              </Autocomplete>
              <Autocomplete>
                <input
                  type="text"
                  placeholder="To"
                  className="border border-blue-500 focus:ring-blue-500 outline-none ring-offset-2 focus:ring-2 rounded-lg w-full px-2 py-1 text-sm placeholder:text-gray-300 text-gray-300"
                  ref={destinationRef}
                />
              </Autocomplete>
              <button
                className="min-[339px]:col-span-2 min-[500px]:col-span-1 bg-blue-600 hover:bg-blue-800 text-white w-full px-3 py-1 grid h-9 rounded-lg cursor-pointer"
                onClick={() => calculateRoute()}>
                Get Directions
              </button>
              <p className="text-white text-sm min-[339px]:text-[1rem]">
                <strong>Distance:</strong> {distance || "-"}
              </p>
              <p className="text-white text-sm min-[339px]:text-[1rem]">
                <strong>Duration:</strong> {duration || "-"}
              </p>
              <div className="flex gap-2 min-[339px]:col-span-2 min-[500px]:col-span-1 justify-end">
                <button
                  className="reset-btn text-lg text-green500 cursor-pointer w-8 h-8 bg-gray-200 flex justify-center items-center rounded-full"
                  onClick={() => clearRoute()}>
                  <FaTrash />
                </button>
                <button
                  className="reset-btn text-lg text-green500 cursor-pointer w-8 h-8 bg-gray-200 flex justify-center items-center rounded-full"
                  onClick={() => map?.panTo(center)}>
                  <IoIosSend />
                </button>
              </div>
            </div>
          </div>
        )}
        <div className="relative bg-gray-100 dark:bg-gray-700 h-164 rounded-lg flex items-center justify-center overflow-hidden">
          {isLoaded ? (
            <GoogleMap
              center={center}
              zoom={15}
              mapContainerStyle={{ width: "100%", height: "100%" }}
              options={{
                zoomControl: false,
                cameraControl: false,
                streetViewControl: false,
                mapTypeControl: false,
                fullscreenControl: false,
              }}
              onLoad={(map) => setMap(map)}>
              <Marker position={center} />
              {/* You can add multiple markers if need be */}
              {directionResponse && (
                <DirectionsRenderer
                  directions={directionResponse}
                  // options={{
                  //   polylineOptions: {
                  //     strokeColor: "#FF0000",
                  //     strokeWeight: 5,
                  //   },
                  // }}
                />
              )}
            </GoogleMap>
          ) : (
            <NotLoaded />
          )}
        </div>
      </div>
    </section>
  );
}

export default App;
